[package]
name = "seqvex"
version = "0.1.0"
edition = "2024"
description = "A Rust-native machine learning and reinforcement learning framework for sequential, non-IID, and streaming workloads."
license = "Apache-2.0"
repository = "https://github.com/Skybrique-Lab/seqvex"
readme = "README.md"

[workspace]
resolver = "3"

[dependencies]

[[bench]]
name = "numerical"
harness = false

[[bench]]
name = "gru"
harness = false

[[bench]]
name = "linear_regression"
harness = false

[[bench]]
name = "rls"
harness = false

[[bench]]
name = "decision_tree"
harness = false